### ISSUE TITLE
VIDEOTORIUM videos have '?' characters on title

### ISSUE THREAD

**Issue by Alfro** [teltek/PuMuKIT2-geant-bundle#101]
Some videotorium videos have '?' characters, as if they couldn't be parsed properlty.

I don't know if this is an issue with the Search API or if it is a problem with the original metadata.

**Screen captures:**

In Géant Portal:
![videotorium_error](https://cloud.githubusercontent.com/assets/11334172/13566965/7e1c59a6-e458-11e5-877d-ed9f569d55bb.png)

In the Search API:
![videotorium_rerror](https://cloud.githubusercontent.com/assets/11334172/13567032/ffa07bec-e458-11e5-8fb6-d8c8349ce027.png)

**Comment by vogias** [comment]
I am afraid this is a problem comming directly from the [Videotorium repository](http://oai.videotorium.hu/videotorium/dataprovider?verb=ListRecords&metadataPrefix=oai_dc)

**Comment by vogias** [comment]
Videotorium is corrected by data provider and reharvested, please re-index when possible

**Comment by vogias** [comment]
Done.Should be closed

**Comment by Alfro** [comment]
Checked.
Videotorium is back on production and with no weird characters.
Closing issue
