### ISSUE TITLE
WebTVBundle: Changing the webpage title/description

### ISSUE THREAD

**Issue by Alfro** [teltek/PuMuKIT2-geant-bundle#13]
- Replace _GÉANT WebTV_ by _eduOER_ as the webpage title. _By Peter_
- Replace _Geant Web TV_ by Geant OER\* as the tab title. _By Kirsten_

**Comment by vogias** [comment]
@Alfro this is already implemented

**Comment by Alfro** [comment]
True. Implemented on commits: (70cfafe, 792b2dc ) and merged on #50
Closing issue.
