### ISSUE TITLE
GeantWebTVBundle: Change 'repository catalogue' description text

### ISSUE THREAD

**Issue by Alfro** [teltek/PuMuKIT2-geant-bundle#2]
Replace the description text by a different one. Suggested by Ilias. 
We have to ask them which text should be add there instead of the current one.

**Comment by Alfro** [comment]
_Kirsten added:_ Don’t say ‘this service’ but say Geant OER. This is more personal.

**Comment by vogias** [comment]
@Alfro This should be closed
