### ISSUE TITLE
Very long repositories names break the design.

### ISSUE THREAD

**Issue by Alfro** [teltek/PuMuKIT2-geant-bundle#21]
After the new changes on the feed, we realised that really long names for a repository would break the thumbnail design and appear on top of the 'date'.

**Comment by vogias** [comment]
@Eielef So shall we keep the long more informative names or switch back to the previous ones?

**Comment by vgoya** [comment]
Please keep the old short names.

We will work on this here:
https://github.com/teltek/PuMuKIT2-geant-bundle/issues/23
