### ISSUE TITLE
Improve "Repository Catalog" page

### ISSUE THREAD

**Issue by vgoya** [teltek/PuMuKIT2-geant-bundle#23]
Improve the "Repository Catalog " page adding per Repository:
- Long-title
- Description 
- Custom Thumbnail / Logo

These data for each Repo will be stored in GitHub and synchronized with the Portal by the daily data synchronization script.

**Comment by Alfro** [comment]
Now json files can be added to 'Resources/data/repos_data/' to add:
- Title
- Description
- Logo
  to the Repository Catalog listing.

If not json is added, the default image and title will be used.
