### ISSUE TITLE
UNED videos can't be viewed.

### ISSUE THREAD

**Issue by Alfro** [teltek/PuMuKIT2-geant-bundle#28]
The videos coming from the Uned feed aren't being viewed on the portal. This is an issue with their format being 'video/mp4' even though they have an embed url. Other repositories may have the same problem.

**Comment by Alfro** [comment]
@vogias Can you try to harvest UNED again? We would like to check if the UNED feed is correct now.

**Comment by vogias** [comment]
@Alfro Done

**Comment by Alfro** [comment]
@vogias The feed didn't seem to change. Which feed are you using to harvest UNED?

**Comment by vogias** [comment]
@Alfro i harvest using RSS the channels are the following:
https://canal.uned.es/2010/arca.xml,
https://canal.uned.es/2009/arca.xml,
https://canal.uned.es/1991/arca.xml,
https://canal.uned.es/1960/arca.xml,
https://canal.uned.es/1974/arca.xml,
https://canal.uned.es/1968/arca.xml,
https://canal.uned.es/1964/arca.xml,
https://canal.uned.es/1973/arca.xml,
https://canal.uned.es/1971/arca.xml,
https://canal.uned.es/1970/arca.xml,
https://canal.uned.es/1951/arca.xml,
https://canal.uned.es/1965/arca.xml,
https://canal.uned.es/2008/arca.xml,
https://canal.uned.es/2007/arca.xml,
https://canal.uned.es/1997/arca.xml,
https://canal.uned.es/1996/arca.xml,
https://canal.uned.es/1999/arca.xml,
https://canal.uned.es/2000/arca.xml,
https://canal.uned.es/1998/arca.xml,
https://canal.uned.es/2012/arca.xml,
https://canal.uned.es/2011/arca.xml,
https://canal.uned.es/2013/arca.xml,
https://canal.uned.es/1962/arca.xml,
https://canal.uned.es/1978/arca.xml,
https://canal.uned.es/1989/arca.xml,
https://canal.uned.es/1977/arca.xml,
https://canal.uned.es/2015/arca.xml,
https://canal.uned.es/2002/arca.xml,
https://canal.uned.es/2004/arca.xml,
https://canal.uned.es/2003/arca.xml,
https://canal.uned.es/2005/arca.xml,
https://canal.uned.es/2001/arca.xml,
https://canal.uned.es/2006/arca.xml,
https://canal.uned.es/2014/arca.xml,
https://canal.uned.es/1987/arca.xml,
https://canal.uned.es/1988/arca.xml,
https://canal.uned.es/1995/arca.xml,
https://canal.uned.es/1994/arca.xml,
https://canal.uned.es/1993/arca.xml,
https://canal.uned.es/1986/arca.xml,
https://canal.uned.es/1981/arca.xml,
https://canal.uned.es/1990/arca.xml,
https://canal.uned.es/1992/arca.xml,
https://canal.uned.es/1984/arca.xml,
https://canal.uned.es/1975/arca.xml,
https://canal.uned.es/2180/arca.xml

**Comment by Alfro** [comment]
@vogias Right, so you are using the `<link>` block, which points to the webpage instead of the resource. The correct field would be the `url` property from the `<media:content>` block 
`<media:content url="https://canal.uned.es/file/29416.mp4">`
Could you change that on the harvesting script?

**Comment by vogias** [comment]
sure

**Comment by vogias** [comment]
@Alfro Done

**Comment by vogias** [comment]
@Alfro this should be closed
