### ISSUE TITLE
GeantWebTVBundle: Repository catalogue. Add description and logo.

### ISSUE THREAD

**Issue by Alfro** [teltek/PuMuKIT2-geant-bundle#3]
**Add a description of each repository.**
This description should be provided on the feed, but it technically could be added manually
- Discuss with OER Geant which field of the script should contain this information, or if it should be added 'manually.

**Add logo of each repository**
The same as above. The solution used to add the description can be used to add the logo as well.
- When the decision is made, the script (and probably the 'repositories' template) must be changed.

**Comment by vogias** [comment]
@Alfro The staging page is not updated at the repository catalogue with new repo information and pics.

**Comment by Alfro** [comment]
@vogias We already detected and solved the issue.

**Comment by vogias** [comment]
@Alfro I think this could be closed
