### ISSUE TITLE
Add TNC videos as a main category on the portal front page

### ISSUE THREAD

**Issue by szegedip** [teltek/PuMuKIT2-geant-bundle#34]
Add TNC videos as the 6th Channel on the homepage of the portal.

**Comment by rubenrua** [comment]
Can we use this image as a poster?

https://www.terena.org/news/img.php?file_id=2521

**Comment by szegedip** [comment]
Wait, I double-check and let you know, or send a new pic.

**Comment by szegedip** [comment]
Sorry, it was too large. Sending one pic again.

Peter

On 12/01/2016 13:40, Peter Szegedi wrote:

> Hi Ruben,
> 
> We should pick some more neutral picture with no recognisable people on.
> Take a look at the ones attached. I would prefer:
> 
> Monday 15 June IMG_8433.jpg
> 
> Cheers,
> Peter
> 
> On 12/01/2016 11:57, Ruben Gonzalez wrote:
> 
> > Can we use this image as a poster?
> > 
> > https://www.terena.org/news/img.php?file_id=2521
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/teltek/PuMuKIT2-geant-bundle/issues/34#issuecomment-170875520.

## 

Peter Szegedi
PROJECT DEVELOPMENT OFFICER
GÉANT - Amsterdam office
T: +31 (0) 20 530 4488

Networks • Services • People
Learn more at www.geant.org

GÉANT is the collective trading name of the GÉANT Association in
Amsterdam, NL, and of GEANT Limited in Cambridge, UK.

The GÉANT Association is a non-profit organisation registered under
Dutch law through the Chamber of Commerce in Amsterdam, registration

## number 40535155.

**Comment by szegedip** [comment]
I sent you a new image that you can crop and use.

**Comment by rubenrua** [comment]
Preview:

![screenshot from 2016-01-12 14 57 02](https://cloud.githubusercontent.com/assets/195745/12265325/c729896c-b93c-11e5-873a-c86ce786de79.png)
