### ISSUE TITLE
Update portal link in the OER site.

### ISSUE THREAD

**Issue by rubenrua** [teltek/PuMuKIT2-geant-bundle#36]
The portal link in the [OER site](https://oer.geant.org/) is wrong. 

The OER portal should link to the [production environment](https://portal.oer.geant.org/) instead of the [test environment](https://snf-683722.vm.okeanos.grnet.gr/).

**Comment by vogias** [comment]
Please assign this @szegedip that is responsible for the site

**Comment by szegedip** [comment]
fixed

**Comment by vogias** [comment]
@rubenrua this should be closed
