### ISSUE TITLE
Add Warning sign to objects with no date.

### ISSUE THREAD

**Issue by Alfro** [teltek/PuMuKIT2-geant-bundle#42]
After the last changes in #5, there will be objects with a date that is not the object's date (01/01/1970).
Add a warning sign to said objects.

**Comment by Alfro** [comment]
The text we added as a warning is "This object's date could not be correctly added."
Is it correct enough, or should we change it? @vgoya Can you verify this?

**Comment by vogias** [comment]
@Alfro This could be closed
