### ISSUE TITLE
ELTE videos were not imported (no valid playable resource found)

### ISSUE THREAD

**Issue by Alfro** [teltek/PuMuKIT2-geant-bundle#43]
@vogias 
Executing the last sync on the staging environment we saw no ELTE videos were imported.
The reason is the strange url format in the feed. They have two items:

```
manifestations: {
    items: [
        {
            broken: false,
            url: "http://hdl.handle.net/10831/10968"
        },
        {
            broken: false,
            url: "LOMS: https://edit.elte.hu/xmlui/bitstream/10831/10968/1/T%C3%89GLATORNA.flv"
        }
    ],
    ...
}
```

The first is the url to a page, and the second the actual .flv video. A normal 'manifestations' file has the following structure:

```
manifestations: {
    items: {
        broken: false,
        url: "http://youtu.be/M1rKp51EUA0"
    },
    ...
}
```

**Issues:**
- Is this an error in this particular feed, or should the script expect 'items' to have more than one element sometimes?
- Should we read all the possible urls and parse them to get the preferred one? (The file is preferred to the link to the page)
- Also, the "LOMS" text in front of the url breaks it. Should we remove it too or is it better to let ELTE know and let them fix the url strings on their feeds?

**Comment by vogias** [comment]
@Alfro Thanks for the info. I will try to fix it during harvesting.I will keep the flv only URL.

**Comment by vogias** [comment]
@Alfro Done!

**Comment by Alfro** [comment]
@vogias Great! We will execute the script again ASAP and check the videos are playing correctly.

**Comment by Alfro** [comment]
ELTE videos were correctly imported now. Closing issue.

**Comment by silviabf** [comment]
Steps:
- Go to: https://snf-683722.vm.okeanos.grnet.gr/searchmultimediaobjects/ELTE
- Click on any video (using chrome navigator)

Problem: When you click on a video instead of play it, a window to download the video is opens.
And as you can see in the attached capture, the dates seem correct but a warning is shown.
![capture_elte](https://cloud.githubusercontent.com/assets/11191010/12351256/906196a8-bb7c-11e5-85e8-1c90eb474184.png)

**Comment by Alfro** [comment]
Alright, I modified the script to mark as 'playable' the flv files. They won't be visible if the user is using a mobile phone though.

**Comment by vogias** [comment]
@Alfro This could be closed
