### ISSUE TITLE
Show objects on 'Latest Uploads'

### ISSUE THREAD

**Issue by Alfro** [teltek/PuMuKIT2-geant-bundle#44]
In order to show objects at 'Latest Uploads'
- Add 'publicDate' to newly harvested mmobjs as the date they were haversted at.
- Add command to reset mmobjs 'publicDate' for already existing objects. (Execute it once)
- View on the portal the 'Latest Uploads' as the last X mmobjs sorted by 'PublicDate'

**Comment by Alfro** [comment]
This is also implemented, and should be on staging soon.

**Comment by silviabf** [comment]
This bug continues happening

**Comment by silviabf** [comment]
Bug fixed. I close the issue.
