### ISSUE TITLE
Contact page: link to Cambridge office go to a non-existing page

### ISSUE THREAD

**Issue by silviabf** [teltek/PuMuKIT2-geant-bundle#45]
Steps:
- Go to Contact page: https://snf-683722.vm.okeanos.grnet.gr/contact
- Click on link: Visiting_DANTE

Problem: You achieve: The page you're looking for doesn't exist.

**Comment by vogias** [comment]
@Alfro I have already recreated the contact page based on the link http://www.geant.org/Contacts/Pages/Home.aspx
I will create a pull request at the end of the day

**Comment by Alfro** [comment]
Pull request merged. Will be on preproduction soon.

**Comment by silviabf** [comment]
New Contact page is OK on preproduction. I close the issue.
