### ISSUE TITLE
Broken pictures in videos from VIGO_RSS

### ISSUE THREAD

**Issue by silviabf** [teltek/PuMuKIT2-geant-bundle#46]
Steps:
- Go to: https://snf-683722.vm.okeanos.grnet.gr/searchmultimediaobjects/VIGO_RSS

Problem: The last 8 videos have broken images as we can see in the attached capture
![capture_vigo_rss](https://cloud.githubusercontent.com/assets/11191010/12350910/4409b922-bb7a-11e5-9136-682437964ef6.png)

**Comment by Alfro** [comment]
That is an issue with the original feed. The url http://dls2.uvigo.es/static/itunes/pics/1050.jpg returns a 404. We will look on this issue on the future.

For future cases, we could implement #51 to have a default 'No Image' picture.

**Comment by Alfro** [comment]
Those particular pictures were restored on UVigo.
Closing issue.
