### ISSUE TITLE
WebTV Bundle: Repository catalogue: Wrong alphabetical order

### ISSUE THREAD

**Issue by silviabf** [teltek/PuMuKIT2-geant-bundle#48]
Steps:
- Go to: https://snf-683722.vm.okeanos.grnet.gr/catalog/by_repository
- Go down to the end of the page

Problem: As you can see in the attached capture. There are repeated letters and they are messy.
![capture_repository](https://cloud.githubusercontent.com/assets/11191010/12351661/89a21556-bb7f-11e5-9f7c-84ccc602ce67.png)

**Comment by Alfro** [comment]
I think this is an issue with the #23 feature and the difference between the repo code and the title.
I will check it out.

**Comment by silviabf** [comment]
Fixed in preproduction. I close the issue.
