### ISSUE TITLE
GeantWebTVBundle: Wrong link in the breadcrumbs

### ISSUE THREAD

**Issue by silviabf** [teltek/PuMuKIT2-geant-bundle#63]
Steps:
- Go to Repository Catalogue
- Select Campus do Mar
- Click on any video
- Then click on the breadcrumb of CAMPUSDOMAR

Problem: The page shown is a strange version of the repository of Campus do Mar. The page must be the same as if you go by Repository Catalogue.

**Comment by Alfro** [comment]
This was fixed with the previous commit. We are about to deploy it to the staging env.

**Comment by silviabf** [comment]
Fixed in snf-683722.vm.okeanos.grnet.gr. The breadcrumbs are correct now.
