### ISSUE TITLE
TNC videos can't be viewed on the portal

### ISSUE THREAD

**Issue by Alfro** [teltek/PuMuKIT2-geant-bundle#65]
The url for TNC videos on the feed changed to this format 'hdl.grnet.gr/11239/eduOER_TNC_949595874'

Now when clicking on a TNC video it shows a 404 error.

**Comment by Alfro** [comment]
**To do:**
- Make controller more robust by adding 'http://' to no absolute urls. (In case another url has the same problem in the future)
- Fix TNC feed to correct the url.

**Comment by Alfro** [comment]
@vogias Is there any reason why the feed was changed?
Also we need to have into account that with the current url (even adding the https:// bit) we can't get the youtube iframe to embed it on the portal. (Instead it would redirect to youtube)

**Comment by vogias** [comment]
@Alfro TNC repository is a test case of using persistent identifiers (see HANDLE systems) for metadata repositories.It is a strategic plan from project perspective to use PIDs. Do you think there is a possibility to  find a workaround or should i inform Peter and Ilias about that?

**Comment by Alfro** [comment]
@vogias There is a workaround we could do:
- Currently, the url on 'hdl.grnet.gr' is redirecting to the **youtube portal**.
- If they redirected to the **youtube iframe** directly (_https://www.youtube.com/embed/LskEi19sZkM_ instead of _https://www.youtube.com/watch?v=LskEi19sZkM_ for example) we can use them to embed the video on Géant and still keep the 'hdl' url.

**Comment by vogias** [comment]
@Alfro Ok, i'll see what i can do. What about the other repositories that are non-youtube related. Are we going to have the same problem?

**Comment by Alfro** [comment]
@vogias Some issues will arise. But it is something we have been doing in other PuMuKIT platforms (redirecting to files or iframes) without mayor difficulties.

We would have to change the script logic though, and make it rely exclusively on the 'format' field, so it would be mandatory that this field is correct. (Currently I am parsing the url when the 'format' field doesn't exist or it doesn't give me enough information)

**Comment by vgoya** [comment]
@vogias I do think that this Persistent-ID thing is very interesting feature but it should be tackled in the future not in this very stage of the project, We are trying now to close a minimum viable project and I dont  think that feature is a must. But may be worth to check this with Ilias and/or Peter. What do you think ?

**Comment by vogias** [comment]
@vgoya Sensible thinking. I currently reverted the TNC data to the previous version, so after a reindexing there will be no problem. In parallel i will think of viable solutions in order not to break the portal but also not compromise the project.

**Comment by vgoya** [comment]
@vogias Thank you !

**Comment by vogias** [comment]
@vgoya @Alfro One solution i came up, is to change the identifier element of the search API with the created PID and let the location hold only the actual URL of the Learning Object. Please check a [TNC example](https://services.oer.geant.org/search/v1/akif?set=TNC). Do you think this is ok from Portal perspective and won't break anything?

**Comment by Alfro** [comment]
@vogias Changing only the identifier won't break anything.

However, have into account that if an identifier is changed on the search API, the PuMuKIT script will think it's a new object and create it again, also blocking the old one (since its ID doesn't exist anymore).

**Comment by vogias** [comment]
@Alfro So the worst case scenario, is a full re-indexing and maybe a double sized index?

**Comment by Alfro** [comment]
@vogias Yes.
We can always make a command to remove the 'Blocked' elements though.

**Comment by vogias** [comment]
@Alfro this should be closed
