### ISSUE TITLE
PRACE, PSNC and FCCN videos can't be viewed on the portal

### ISSUE THREAD

**Issue by silviabf** [teltek/PuMuKIT2-geant-bundle#67]
Steps:
- Go to Repository of PRACE, PSNC or FCCN in snf-683722.vm.okeanos.grnet.gr
- Click on any Video

Problem: A new window is opened that shows: this web is not avaliable.

**Comment by silviabf** [comment]
This bug happens with all Repositories with external links: PRACE,PSNC, FCCN, MAOR, CRETE,..

**Comment by rubenrua** [comment]
`https://snf-683722.vm.okeanos.grnet.gr/video/566ebd0435f5251b5f8bdf4f` redirect to `http://https://educast.fccn.pt/vod/clips/17s6luois2/link_box`

Bug in [MultimediaObjectController](https://github.com/teltek/PuMuKIT2-geant-bundle/blob/1.0.0-RC20/Controller/MultimediaObjectController.php#L23) with [strpos](http://php.net/manual/es/function.strpos.php).

RTFM :)

**Comment by silviabf** [comment]
Bug is fixed in snf-683722.vm.okeanos.grnet.gr. I close the issue
