### ISSUE TITLE
The geant Search API throws a 500 Error when adding a 'sort_by' parameter

### ISSUE THREAD

**Issue by Alfro** [teltek/PuMuKIT2-geant-bundle#72]
This is not a blocker bug, since we are not using this feature at the moment.

Example Url: https://services.oer.geant.org/search/v1/akif/?q=*&sort_by=identifier
![search_api_error_500](https://cloud.githubusercontent.com/assets/11334172/12942975/859c6ccc-cfde-11e5-8be7-096e40cccedc.png)

**Comment by Alfro** [comment]
It is probably just a typo. The SortOrder constants seems to be ASC and DESC (in capital letters):
http://javadoc.kyubu.de/elasticsearch/v1.0.2/org/elasticsearch/search/sort/SortOrder.html

**Comment by vogias** [comment]
Thanks for the feedback! The search API is fixed, when i deploy the new version i'll let you know.

**Comment by vogias** [comment]
ok done!

**Comment by Alfro** [comment]
@vogias Cool!
Btw, when 'sort_by' is set to a parameter that doesn't exist the API returns a 500 error.
Besides that, it seems to work just fine! :)
Would you like to change that too, or should I close the issue already?

**Comment by vogias** [comment]
ok, fixed. Please close the issue.
