### ISSUE TITLE
The geant Search API doesn't return any results when filtering by specific 'sets'

### ISSUE THREAD

**Issue by Alfro** [teltek/PuMuKIT2-geant-bundle#73]
Out of the sets listed on https://services.oer.geant.org/search/v1/akif/?q=*&facets=set
![search_api_sets](https://cloud.githubusercontent.com/assets/11334172/12943279/87797114-cfe0-11e5-8b8e-1f71d4dadd42.png)
The following sets don't return any results when filtering by 'set'
VIDEOTORIUM
https://services.oer.geant.org/search/v1/akif/?q=*&set=VIDEOTORIUM
![videotorium](https://cloud.githubusercontent.com/assets/11334172/12943327/d3d2927a-cfe0-11e5-8186-4e9989d8a691.png)
STANFORD
https://services.oer.geant.org/search/v1/akif/?q=*&set=STANFORD
![stanford](https://cloud.githubusercontent.com/assets/11334172/12943394/42111dce-cfe1-11e5-811a-b546ffe05b27.png)

This is not a blocker bug.

**Comment by vogias** [comment]
This is truly weird! I don't even know how to debug this :-)

**Comment by vogias** [comment]
#73 this is solved. You could use lower case set input in case the upper case does not work.

**Comment by Alfro** [comment]
This feature seems to be working propertly.
Using always lowercase gives a consistent result for all the current sets.
I'll close the issue.
