### ISSUE TITLE
Wrong order in latest uploads section

### ISSUE THREAD

**Issue by silviabf** [teltek/PuMuKIT2-geant-bundle#81]
Steps:
- Go to snf-683722.vm.okeanos.grnet.gr
- Go to Latest Uploads

Problem: As you can see in the attached capture, the order of the videos seems to be wrong. The videos are ordered by publishing date but the date shown is recording date, and it's very strange to see it.
![latest_uploads](https://cloud.githubusercontent.com/assets/11191010/13140026/06a315e4-d630-11e5-979a-9c415e15c1b6.png)

**Comment by vgoya** [comment]
We may need to specify "Recorded: Date" in the UI to avoid confusion with "Added date"

@Alfro please, add here a mockup of an improved UI

**Comment by Alfro** [comment]
- I reduced the size of the Date field font
- I added the text 'Recorded:' to the left.

![new_design_2](https://cloud.githubusercontent.com/assets/11334172/13141449/b5597fae-d637-11e5-8323-967829d05c84.png)

We also tried to add it a border to see how it looks (making the 'Viewed' be more clearly part of the thumbnail)
![new_design](https://cloud.githubusercontent.com/assets/11334172/13141521/0f8dc2be-d638-11e5-96a0-948ac767d2fc.png)

**Comment by vgoya** [comment]
@vogias / Ilias  What do you think about this "boxed" idea ?

**Comment by vogias** [comment]
@vgoya Sure why not. Is it possible to paste a screenshot of a mouse hovering event over a video panel?

**Comment by vogias** [comment]
@vgoya ok i implemented this. Please check the pull requests.

**Comment by vgoya** [comment]
Great, thank you

**Comment by Alfro** [comment]
Both the borders and the bugfix are implemented on 1.0.2
Closing issue
