### ISSUE TITLE
Change date label on listing page from '1970'

### ISSUE THREAD

**Issue by vogias** [teltek/PuMuKIT2-geant-bundle#86]
When repository date is not determined, the label will be 'N/A' with a explanation tooltip instead of '1970' value

**Comment by vogias** [comment]
I will implement it

**Comment by vogias** [comment]
![86_screenshot](https://cloud.githubusercontent.com/assets/2890621/13349000/a978043c-dc7f-11e5-849e-6aca25027e26.png)

**Comment by vgoya** [comment]
During the virtual meeting we decided not to do this change, AFAIK

To do it properly we need a "N/A date" at all levels included the faceted search form. Now you choose 1970 in the faceted search and in the outcome you will read "N/A" but any other year will have a different behaviour

**Comment by vogias** [comment]
@vgoya What do you think of a solution like the following?
![example](https://cloud.githubusercontent.com/assets/2890621/13422208/df25cc62-df9b-11e5-82c3-03fee520ab7b.png)

**Comment by vgoya** [comment]
Much better solution, yes.

**Comment by Alfro** [comment]
This is already implemented on 1.0.2
Closing issue
