### ISSUE TITLE
WebTVBundle: Lateral menu. Names and ordering

### ISSUE THREAD

**Issue by Alfro** [teltek/PuMuKIT2-geant-bundle#9]
Some changes have been suggested to the menu:
- Change the magenta color by dark-blue.
- Replace 'Go to Advanced search' by 'Advanced search'.
- Put 'By subject catalogue' before 'By repository catalogue'.

**Comment by Alfro** [comment]
Eli suggested the following order:
Remove the title. ('Menu' text).
·        (home)-change into an icon, consider a different location (somewhere on the top…)
·        Subject catalogue
·        Repository catalogue
·        Language catalogue
·        Latest uploads
·        About (including the previous info section's content)
·        FAQ – delete the s and the apostrophe, put the questions first with hyperlinks to the answers, or put the answers in a collapsible format, hidden at first sight.
·        Contact us – add more contact details.

**Comment by vogias** [comment]
@Alfro  this could be closed
