### ISSUE TITLE
Video sharing capability is missing from TNC repository

### ISSUE THREAD

**Issue by vogias** [teltek/PuMuKIT2-geant-bundle#95]

**Comment by rubenrua** [comment]
No `track.id` in youtube videos.

See: https://github.com/teltek/PuMuKIT2-geant-bundle/blob/1.0.1/Resources/views/MultimediaObject/share.html.twig#L45

**Comment by rubenrua** [comment]
Fixed in tag `1.0.2`

**Comment by Alfro** [comment]
Fixed. Closing issue.
